// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package facedetection.actions;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import facedetection.proxies.FaceLocation;

public class JA_BlurBoxes extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __SoureImage;
	private facedetection.proxies.Photo SoureImage;
	private IMendixObject __DestinationImage;
	private facedetection.proxies.Photo DestinationImage;
	private java.util.List<IMendixObject> __FaceLocations;
	private java.util.List<facedetection.proxies.FaceLocation> FaceLocations;

	public JA_BlurBoxes(IContext context, IMendixObject SoureImage, IMendixObject DestinationImage, java.util.List<IMendixObject> FaceLocations)
	{
		super(context);
		this.__SoureImage = SoureImage;
		this.__DestinationImage = DestinationImage;
		this.__FaceLocations = FaceLocations;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.SoureImage = __SoureImage == null ? null : facedetection.proxies.Photo.initialize(getContext(), __SoureImage);

		this.DestinationImage = __DestinationImage == null ? null : facedetection.proxies.Photo.initialize(getContext(), __DestinationImage);

		this.FaceLocations = new java.util.ArrayList<facedetection.proxies.FaceLocation>();
		if (__FaceLocations != null)
			for (IMendixObject __FaceLocationsElement : __FaceLocations)
				this.FaceLocations.add(facedetection.proxies.FaceLocation.initialize(getContext(), __FaceLocationsElement));

		// BEGIN USER CODE
		IContext ctx =  getContext();
		try {
			// Get input stream from Mendix object and read into Buffered image
			InputStream fis = Core.getFileDocumentContent(ctx, __SoureImage);
			BufferedImage readOnlyImage = ImageIO.read(fis);
			// New Image, prep for drawing...
			BufferedImage image =
					new BufferedImage(readOnlyImage.getWidth(),readOnlyImage.getHeight(), BufferedImage.TYPE_INT_RGB);

			Graphics gfx = image.getGraphics();
			gfx.drawImage(readOnlyImage, 0, 0, null);
			gfx.dispose();
			
			// A 3x3 kernel that blurs an image
			float[] matrix = new float[2500];
			for (int i = 0; i < 2500; i++)
				matrix[i] = 1.0f/2500.0f;
			Kernel kernel = new Kernel(50, 50, matrix);
			BufferedImageOp op = new ConvolveOp(kernel, ConvolveOp.EDGE_NO_OP,null);

			// Iterate and blur sub images based on each location
			
			for (FaceLocation location : FaceLocations) {
				BufferedImage dest = image.getSubimage(
						(location.getX()),
						location.getY(),
						location.getWidth(),
						location.getHeight());
				ColorModel cm = dest.getColorModel();
				BufferedImage src = new BufferedImage(cm,
						dest.copyData(dest.getRaster().createCompatibleWritableRaster()),
						cm.isAlphaPremultiplied(),
						null)
						.getSubimage(0, 0, dest.getWidth(), dest.getHeight());
				op.filter(src, dest);
			}
			
			
			// Write result to Byte array to be stored back in mx object
			ByteArrayOutputStream output = new ByteArrayOutputStream();
			ImageIO.write(image, "jpg", output);

			//Store in InputStream and Write to Mendix object
			InputStream is = new ByteArrayInputStream(output.toByteArray());
			Core.storeImageDocumentContent(ctx, DestinationImage.getMendixObject(), is, image.getWidth(), image.getHeight());

			// Cleanup
			output.close();
			is.close();

			return true;
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_BlurBoxes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
